spring:
  profiles:
    active: dev
  application:
    name: nycloud-api-gateway

server:
  port: 7000

zuul:
  ribbon:
    eager-load:
      enabled: true
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
  routes:
    login:
      path: /auth/**
      ignoredPatterns: /consul
      serviceId: nycloud-auth-server
      sensitiveHeaders: Cookie,Set-Cookie
    admin:
      path: /admin/**
      ignoredPatterns: /consul
      serviceId: nycloud-admin
      sensitiveHeaders: Cookie,Set-Cookie
  retryable: true

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
auth:
  permitall:
    -
      pattern: /auth/login
    -
      pattern: /**/public/**