spring:
  cloud:
    consul:
      discovery:
        preferIpAddress: true
        enabled: true
        register: true
        service-name: nycloud-api-gateway
        health-check-interval: 10s
        health-check-timeout: 20s
        heartbeat:
          enabled: true
        ip-address: ${HOST_ADDRESS:localhost}
        port: ${SERVER_PORT:${server.port}}
        lifecycle:
          enabled: true
        scheme: http
        prefer-agent-address: false
        register-health-check: true
        tags: master
        query-passing: true
      retry:
        initial-interval: 1000
        max-attempts: 4
        max-interval: 1000
      host: 127.0.0.1
      port: 8500